name: Build Wheel

on:
  push:
    paths:
    - requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create wheel
      run: |
        pip wheel -r requirements.txt -w dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: new-wheel
        path: dist/
